Ecosystem Projects
solana-labs/ecosystem pull request #148
Opened 2021-08-24 17:09 UTC by techpubswriter

Added the fields from the Excel sheet and edited the content.

2021-08-24 17:10 UTC, rmshea commented on projects/akash.md
> +
can you remove these extra lines?

2021-08-24 17:15 UTC, rmshea requested changes
if you remove the whitespace and delete `Untitled-1`, we'll be good to merge.

2021-08-24 17:15 UTC, rmshea commented on projects/Untitled-1
> +@@ -6,7 +6,17 @@
can you remove these?

2021-08-24 17:15 UTC, rmshea commented on projects/Untitled-1
> + cta: "https://medium.com/audius/audius-selects-solana-to-scale-community-owned-music-streaming-8a868db644eb"
missing a "slug"

2021-08-24 17:15 UTC, rmshea commented on projects/akash.md
> +
can you remove the whitespace?

2021-08-24 17:15 UTC, rmshea commented on projects/waves.md
> +Waves is a Crypto-platform for asset/custom token issuance, transfer and trading on the Waves blockchain, with centralised order matching and decentralised settlement.
can you add a comma after transfer? We like Oxford commas :)

2021-08-25 08:29 UTC, techpubswriter commented on projects/Untitled-1
> + cta: "https://medium.com/audius/audius-selects-solana-to-scale-community-owned-music-streaming-8a868db644eb"
I didnt delete "slug"

2021-08-30 01:31 UTC, rmshea approved these changes

2021-08-30 01:31 UTC, merged